services:
  api-gateway:
    container_name: api-gateway
    build:
      context: services
      dockerfile: api_gateway/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - USER_SERVICE_URL=http://user-service:8000/user-service
      - QUEST_SERVICE_URL=http://quest-service:8001/quest-service
      - BOARD_SERVICE_URL=http://board-service:8002/board-service
      - ADVENTURE_SERVICE_URL=http://adventure-service:8003/adventure-service
      - PARTY_SERVICE_URL=http://party-service:8004/party-service
      - REDIS_URL=redis://${REDIS_NAME}:${REDIS_PORT}
      - API_KEY=${API_KEY}
      - INSIDE_API_KEY=${INSIDE_API_KEY}
    depends_on:
      - redis
      - user-service
      - quest-service
      - board-service
      - adventure-service
      - party-service

  user-service:
    container_name: user-service
    build:
      context: services
      dockerfile: user_service/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://${DB_USER}:${DB_PASS}@${DB_NAME}:${DB_PORT}/${DB_NAME}
      - API_KEY=${INSIDE_API_KEY}
      - SECRET=${SECRET}
      - PUBLIC_KEY=${PUBLIC_KEY}
      - PRIVATE_KEY=${PRIVATE_KEY}
    depends_on:
      - db

  quest-service:
    container_name: quest-service
    build:
      context: services
      dockerfile: quest_service/Dockerfile
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql+asyncpg://${DB_USER}:${DB_PASS}@${DB_NAME}:${DB_PORT}/${DB_NAME}
      - API_KEY=${INSIDE_API_KEY}
    depends_on:
      - db

  board-service:
    container_name: board-service
    build:
      context: services
      dockerfile: board_service/Dockerfile
    ports:
      - "8002:8002"
    environment:
      - DATABASE_URL=postgresql+asyncpg://${DB_USER}:${DB_PASS}@${DB_NAME}:${DB_PORT}/${DB_NAME}
      - API_KEY=${INSIDE_API_KEY}
    depends_on:
      - db

  adventure-service:
    container_name: adventure-service
    build:
      context: services
      dockerfile: adventure_service/Dockerfile
    ports:
      - "8003:8003"
    environment:
      - DATABASE_URL=postgresql+asyncpg://${DB_USER}:${DB_PASS}@${DB_NAME}:${DB_PORT}/${DB_NAME}
      - API_KEY=${INSIDE_API_KEY}
    depends_on:
      - db

  party-service:
    container_name: party-service
    build:
      context: services
      dockerfile: party_service/Dockerfile
    ports:
      - "8004:8004"
    environment:
      - DATABASE_URL=postgresql+asyncpg://${DB_USER}:${DB_PASS}@${DB_NAME}:${DB_PORT}/${DB_NAME}
      - API_KEY=${INSIDE_API_KEY}
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}

  redis:
    container_name: redis
    image: redis:7